
// Generated by Cadence Genus(TM) Synthesis Solution 21.10-p002_1
// Generated on: Jan 13 2025 16:36:32 -03 (Jan 13 2025 19:36:32 UTC)

// Verification Directory fv/codificador_pt2262 

module codificador_pt2262(clk, reset, A, D, sync, cod_o);
  input clk, reset;
  input [7:0] A;
  input [3:0] D;
  output sync, cod_o;
  wire clk, reset;
  wire [7:0] A;
  wire [3:0] D;
  wire sync, cod_o;
  wire [7:0] A_01;
  wire [7:0] A_F;
  wire [3:0] estado;
  wire [11:0] pacote;
  wire clk_osc, n_39, n_40, n_41, n_42, n_43, n_44, n_45;
  wire n_46, n_47, n_48, n_49, n_50, n_51, n_52, n_53;
  wire n_54, n_55, n_56, n_57, n_58, n_59, n_60, n_61;
  wire n_62, n_63, n_64, n_65, n_66, n_67, n_68, n_69;
  wire n_70, n_71, n_72, n_73, n_74, n_75, n_76, n_77;
  wire n_78;
  clock_divider_250 clk_div(.clk_in (clk), .reset (reset), .clk_out
       (clk_osc));
  comp_endereco comp_inst(.A (A), .A_01 (A_01), .A_F (A_F));
  DFFRHQX1 \estado_reg[1] (.RN (n_42), .CK (clk_osc), .D (n_78), .Q
       (estado[1]));
  DFFRHQX1 \estado_reg[0] (.RN (n_42), .CK (clk_osc), .D (n_39), .Q
       (estado[0]));
  AND2X1 g2012__2398(.A (n_77), .B (estado[0]), .Y (n_78));
  OAI31X1 g2013__5107(.A0 (pacote[11]), .A1 (pacote[10]), .A2 (n_76),
       .B0 (n_41), .Y (n_77));
  OR4X1 g2014__6260(.A (pacote[9]), .B (pacote[8]), .C (pacote[7]), .D
       (n_75), .Y (n_76));
  DFFRHQX1 cod_o_reg(.RN (n_42), .CK (clk_osc), .D (n_69), .Q (cod_o));
  DFFHQX1 \pacote_reg[3] (.CK (clk_osc), .D (n_71), .Q (pacote[3]));
  DFFHQX1 \pacote_reg[2] (.CK (clk_osc), .D (n_72), .Q (pacote[2]));
  DFFHQX1 \pacote_reg[11] (.CK (clk_osc), .D (n_67), .Q (pacote[11]));
  DFFHQX1 \pacote_reg[4] (.CK (clk_osc), .D (n_70), .Q (pacote[4]));
  DFFHQX1 \pacote_reg[1] (.CK (clk_osc), .D (n_66), .Q (pacote[1]));
  OR4X1 g2021__4319(.A (pacote[5]), .B (pacote[6]), .C (pacote[4]), .D
       (n_48), .Y (n_75));
  DFFHQX1 \pacote_reg[7] (.CK (clk_osc), .D (n_59), .Q (pacote[7]));
  DFFHQX1 \pacote_reg[8] (.CK (clk_osc), .D (n_64), .Q (pacote[8]));
  DFFHQX1 \pacote_reg[9] (.CK (clk_osc), .D (n_68), .Q (pacote[9]));
  DFFHQX1 \pacote_reg[10] (.CK (clk_osc), .D (n_62), .Q (pacote[10]));
  DFFHQX1 \pacote_reg[5] (.CK (clk_osc), .D (n_73), .Q (pacote[5]));
  DFFHQX1 \pacote_reg[6] (.CK (clk_osc), .D (n_74), .Q (pacote[6]));
  OAI2BB1X1 g2028__8428(.A0N (pacote[5]), .A1N (n_47), .B0 (n_51), .Y
       (n_74));
  OAI2BB1X1 g2029__5526(.A0N (A[1]), .A1N (n_45), .B0 (n_54), .Y
       (n_73));
  OAI2BB1X1 g2030__6783(.A0N (D[2]), .A1N (n_45), .B0 (n_57), .Y
       (n_72));
  OAI2BB1X1 g2031__3680(.A0N (D[3]), .A1N (n_45), .B0 (n_58), .Y
       (n_71));
  OAI2BB1X1 g2032__1617(.A0N (A[0]), .A1N (n_45), .B0 (n_55), .Y
       (n_70));
  DFFRHQX1 sync_reg(.RN (n_42), .CK (clk_osc), .D (n_56), .Q (sync));
  DFFHQX1 \pacote_reg[0] (.CK (clk_osc), .D (n_50), .Q (pacote[0]));
  INVXL g2035(.A (n_65), .Y (n_69));
  INVXL g2036(.A (n_63), .Y (n_68));
  INVXL g2037(.A (n_61), .Y (n_67));
  INVXL g2038(.A (n_60), .Y (n_66));
  AOI32X1 g2039__2802(.A0 (pacote[11]), .A1 (estado[0]), .A2 (n_41),
       .B0 (cod_o), .B1 (n_46), .Y (n_65));
  OAI2BB1X1 g2040__1705(.A0N (pacote[7]), .A1N (n_47), .B0 (n_53), .Y
       (n_64));
  AOI222X1 g2041__5122(.A0 (pacote[8]), .A1 (n_47), .B0 (pacote[9]),
       .B1 (n_44), .C0 (A[5]), .C1 (n_45), .Y (n_63));
  OAI2BB1X1 g2042__8246(.A0N (pacote[9]), .A1N (n_47), .B0 (n_49), .Y
       (n_62));
  AOI222X1 g2043__7098(.A0 (pacote[10]), .A1 (n_47), .B0 (pacote[11]),
       .B1 (n_44), .C0 (A[7]), .C1 (n_45), .Y (n_61));
  AOI222X1 g2044__6131(.A0 (pacote[0]), .A1 (n_47), .B0 (pacote[1]),
       .B1 (n_44), .C0 (D[1]), .C1 (n_45), .Y (n_60));
  OAI2BB1X1 g2045__1881(.A0N (pacote[6]), .A1N (n_47), .B0 (n_52), .Y
       (n_59));
  AOI22XL g2046__5115(.A0 (pacote[2]), .A1 (n_47), .B0 (pacote[3]), .B1
       (n_44), .Y (n_58));
  AOI22XL g2047__7482(.A0 (pacote[1]), .A1 (n_47), .B0 (pacote[2]), .B1
       (n_44), .Y (n_57));
  OAI21XL g2048__4733(.A0 (estado[0]), .A1 (n_41), .B0 (n_43), .Y
       (n_56));
  AOI22XL g2049__6161(.A0 (pacote[3]), .A1 (n_47), .B0 (pacote[4]), .B1
       (n_44), .Y (n_55));
  AOI22XL g2050__9315(.A0 (pacote[4]), .A1 (n_47), .B0 (pacote[5]), .B1
       (n_44), .Y (n_54));
  AOI22XL g2051__9945(.A0 (A[4]), .A1 (n_45), .B0 (pacote[8]), .B1
       (n_44), .Y (n_53));
  AOI22XL g2052__2883(.A0 (A[3]), .A1 (n_45), .B0 (pacote[7]), .B1
       (n_44), .Y (n_52));
  AOI22XL g2053__2346(.A0 (A[2]), .A1 (n_45), .B0 (pacote[6]), .B1
       (n_44), .Y (n_51));
  AO22X1 g2054__1666(.A0 (D[0]), .A1 (n_45), .B0 (pacote[0]), .B1
       (n_44), .Y (n_50));
  AOI22XL g2055__7410(.A0 (A[6]), .A1 (n_45), .B0 (pacote[10]), .B1
       (n_44), .Y (n_49));
  OR4X1 g2057__6417(.A (pacote[1]), .B (pacote[3]), .C (pacote[2]), .D
       (pacote[0]), .Y (n_48));
  NOR2XL g2058__5477(.A (n_40), .B (n_44), .Y (n_47));
  OAI22XL g2059__2398(.A0 (estado[1]), .A1 (estado[0]), .B0 (n_41), .B1
       (n_40), .Y (n_46));
  NOR2XL g2060__5107(.A (estado[0]), .B (n_44), .Y (n_45));
  NAND2XL g2061__6260(.A (n_42), .B (n_41), .Y (n_44));
  INVXL g2062(.A (sync), .Y (n_43));
  INVXL g2063(.A (reset), .Y (n_42));
  INVX1 g2064(.A (estado[1]), .Y (n_41));
  INVXL g2065(.A (estado[0]), .Y (n_40));
  NAND2BX1 g2__4319(.AN (n_46), .B (n_77), .Y (n_39));
endmodule

